version: "2"
run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - misspell

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
